export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"

zstyle ':omz:update' frequency 7

plugins=(git)

source $ZSH/oh-my-zsh.sh

# For Claude Code known installation issues on MacOS
export PATH="$HOME/.local/bin:$PATH"

